packages:
  - 'apps/*'
  - 'packages/*'
patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch
overrides:
  fast-uri: ^3.1.8
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true

auditConfig:
  ignoreGhas:
    - GHSA-23c5-xmqv-rm74
    - GHSA-23hp-3jrh-7fpw
    - GHSA-2883-xcg3-v3hh
    - GHSA-28wg-ghj8-5hjv
    - GHSA-2g4f-4pwh-qvx6
    - GHSA-2v37-7h3g-55p8
    - GHSA-2xp9-vwfh-vxw4
    - GHSA-34x7-hfp2-rc4v
    - GHSA-3644-q5cj-c5c7
    - GHSA-36qx-fr4f-26g5
    - GHSA-36xv-jgw5-4q75
    - GHSA-3jxr-9vmj-r5cp
    - GHSA-3p4h-7m6x-2hcm
    - GHSA-3ppc-4f35-3m26
    - GHSA-3v7f-55p6-f55p
    - GHSA-3x4c-7xq6-9pq8
    - GHSA-4342-x723-ch2f
    - GHSA-4633-3j49-mh5q
    - GHSA-4c39-4ccg-62r3
    - GHSA-4c8g-83qw-93j6
    - GHSA-4mjr-xmp4-gh2g
    - GHSA-52cp-r559-cp3m
    - GHSA-535w-7cp7-47q4
    - GHSA-5528-5vmv-3xc2
    - GHSA-5j59-xgg2-r9c4
    - GHSA-5j98-mcp5-4vw2
    - GHSA-5p4m-2wfm-xmqj
    - GHSA-5v7r-6r5c-r473
    - GHSA-6j4f-fj2g-mc7p
    - GHSA-68g3-v927-f742
    - GHSA-6g55-p6wh-862q
    - GHSA-72gw-mp4g-v24j
    - GHSA-73wf-gq98-2v4g
    - GHSA-7gfc-8cq8-jh5f
    - GHSA-7m27-7ghc-44w9
    - GHSA-7p8r-x3mc-p8w7
    - GHSA-7r86-cg39-jmmj
    - GHSA-7rqj-j65f-68wh
    - GHSA-83g3-92jg-28cx
    - GHSA-89xv-2m56-2m9x
    - GHSA-8h8q-6873-q5fj
    - GHSA-8qq5-rm4j-mr97
    - GHSA-8x88-c5mf-7j5w
    - GHSA-955p-x3mx-jcvp
    - GHSA-9g9p-9gw9-jx7f
    - GHSA-9ppj-qmqm-q256
    - GHSA-c2c7-rcm5-vvqj
    - GHSA-c4j6-fc7j-m34r
    - GHSA-c83g-rgw3-j3cx
    - GHSA-f23m-r3pf-42rh
    - GHSA-f65p-4m7j-42xc
    - GHSA-f82v-jwr5-mffw
    - GHSA-ffhc-5mcf-pf4q
    - GHSA-fph4-wmhf-6fwf
    - GHSA-fw9q-39r9-c252
    - GHSA-fxqj-rqcc-2cmp
    - GHSA-g5qg-72qw-gw5v
    - GHSA-g77x-44xx-532m
    - GHSA-ggv3-7p47-pfv8
    - GHSA-gp8f-8m3g-qvj9
    - GHSA-gvwx-54wh-qm9j
    - GHSA-gx5p-jg67-6x7h
    - GHSA-h25m-26qc-wcjf
    - GHSA-h64f-5h5j-jqjh
    - GHSA-h67p-54hq-rp68
    - GHSA-j47w-4g3g-c36v
    - GHSA-jqff-g426-hqxp
    - GHSA-jrc7-96c5-q579
    - GHSA-m99w-x7hq-7vfj
    - GHSA-mh99-v99m-4gvg
    - GHSA-mwv6-3258-q52c
    - GHSA-p293-qw3h-jr36
    - GHSA-p9j2-gv94-2wf4
    - GHSA-ph9p-34f9-6g65
    - GHSA-q2hr-2g5m-vwhr
    - GHSA-q4gf-8mx6-v5v3
    - GHSA-q8mj-m7cp-5q26
    - GHSA-qffp-2rhf-9h96
    - GHSA-qhr7-859c-m2p7
    - GHSA-qx2v-qp2m-jg93
    - GHSA-r28c-9q8g-f849
    - GHSA-r292-9mhp-454m
    - GHSA-r399-636x-v7f6
    - GHSA-r5fr-rjxr-66jc
    - GHSA-r6q2-hw4h-h46w
    - GHSA-rgw5-rvv9-x895
    - GHSA-rr7j-v2q5-chgv
    - GHSA-v2hh-gcrm-f6hx
    - GHSA-v52c-386h-88mc
    - GHSA-vfj7-8cjw-p6xm
    - GHSA-vmf3-w455-68vh
    - GHSA-w5hq-g745-h8pq
    - GHSA-w5vr-8v7q-w6rv
    - GHSA-w8wr-v893-vjvp
    - GHSA-wc9g-mqfw-jrwm
    - GHSA-wfc6-r584-vfw7
    - GHSA-x445-f3h2-j279
    - GHSA-x5fp-wj9c-mxmx
    - GHSA-xf7r-hgr6-v32p
    - GHSA-xmf8-cvqr-rfgj
    - GHSA-xv57-4mr9-wg8v
    - GHSA-xxjr-mmjv-4gpg
  ignoreGhsas:
    - GHSA-23c5-xmqv-rm74
    - GHSA-23hp-3jrh-7fpw
    - GHSA-2883-xcg3-v3hh
    - GHSA-28wg-ghj8-5hjv
    - GHSA-2g4f-4pwh-qvx6
    - GHSA-2v37-7h3g-55p8
    - GHSA-2xp9-vwfh-vxw4
    - GHSA-34x7-hfp2-rc4v
    - GHSA-3644-q5cj-c5c7
    - GHSA-36qx-fr4f-26g5
    - GHSA-36xv-jgw5-4q75
    - GHSA-3jxr-9vmj-r5cp
    - GHSA-3p4h-7m6x-2hcm
    - GHSA-3ppc-4f35-3m26
    - GHSA-3v7f-55p6-f55p
    - GHSA-3x4c-7xq6-9pq8
    - GHSA-4342-x723-ch2f
    - GHSA-4633-3j49-mh5q
    - GHSA-4c39-4ccg-62r3
    - GHSA-4c8g-83qw-93j6
    - GHSA-4mjr-xmp4-gh2g
    - GHSA-52cp-r559-cp3m
    - GHSA-535w-7cp7-47q4
    - GHSA-5528-5vmv-3xc2
    - GHSA-5j59-xgg2-r9c4
    - GHSA-5j98-mcp5-4vw2
    - GHSA-5p4m-2wfm-xmqj
    - GHSA-5v7r-6r5c-r473
    - GHSA-6j4f-fj2g-mc7p
    - GHSA-68g3-v927-f742
    - GHSA-6g55-p6wh-862q
    - GHSA-72gw-mp4g-v24j
    - GHSA-73wf-gq98-2v4g
    - GHSA-7gfc-8cq8-jh5f
    - GHSA-7m27-7ghc-44w9
    - GHSA-7p8r-x3mc-p8w7
    - GHSA-7r86-cg39-jmmj
    - GHSA-7rqj-j65f-68wh
    - GHSA-83g3-92jg-28cx
    - GHSA-89xv-2m56-2m9x
    - GHSA-8h8q-6873-q5fj
    - GHSA-8qq5-rm4j-mr97
    - GHSA-8x88-c5mf-7j5w
    - GHSA-955p-x3mx-jcvp
    - GHSA-9g9p-9gw9-jx7f
    - GHSA-9ppj-qmqm-q256
    - GHSA-c2c7-rcm5-vvqj
    - GHSA-c4j6-fc7j-m34r
    - GHSA-c83g-rgw3-j3cx
    - GHSA-f23m-r3pf-42rh
    - GHSA-f65p-4m7j-42xc
    - GHSA-f82v-jwr5-mffw
    - GHSA-ffhc-5mcf-pf4q
    - GHSA-fph4-wmhf-6fwf
    - GHSA-fw9q-39r9-c252
    - GHSA-fxqj-rqcc-2cmp
    - GHSA-g5qg-72qw-gw5v
    - GHSA-g77x-44xx-532m
    - GHSA-ggv3-7p47-pfv8
    - GHSA-gp8f-8m3g-qvj9
    - GHSA-gvwx-54wh-qm9j
    - GHSA-gx5p-jg67-6x7h
    - GHSA-h25m-26qc-wcjf
    - GHSA-h64f-5h5j-jqjh
    - GHSA-h67p-54hq-rp68
    - GHSA-j47w-4g3g-c36v
    - GHSA-jqff-g426-hqxp
    - GHSA-jrc7-96c5-q579
    - GHSA-m99w-x7hq-7vfj
    - GHSA-mh99-v99m-4gvg
    - GHSA-mwv6-3258-q52c
    - GHSA-p293-qw3h-jr36
    - GHSA-p9j2-gv94-2wf4
    - GHSA-ph9p-34f9-6g65
    - GHSA-q2hr-2g5m-vwhr
    - GHSA-q4gf-8mx6-v5v3
    - GHSA-q8mj-m7cp-5q26
    - GHSA-qffp-2rhf-9h96
    - GHSA-qhr7-859c-m2p7
    - GHSA-qx2v-qp2m-jg93
    - GHSA-r28c-9q8g-f849
    - GHSA-r292-9mhp-454m
    - GHSA-r399-636x-v7f6
    - GHSA-r5fr-rjxr-66jc
    - GHSA-r6q2-hw4h-h46w
    - GHSA-rgw5-rvv9-x895
    - GHSA-rr7j-v2q5-chgv
    - GHSA-v2hh-gcrm-f6hx
    - GHSA-v52c-386h-88mc
    - GHSA-vmf3-w455-68vh
    - GHSA-w5hq-g745-h8pq
    - GHSA-w5vr-8v7q-w6rv
    - GHSA-w8wr-v893-vjvp
    - GHSA-wc9g-mqfw-jrwm
    - GHSA-wfc6-r584-vfw7
    - GHSA-x445-f3h2-j279
    - GHSA-x5fp-wj9c-mxmx
    - GHSA-xf7r-hgr6-v32p
    - GHSA-xmf8-cvqr-rfgj
    - GHSA-xv57-4mr9-wg8v
    - GHSA-xxjr-mmjv-4gpg
